version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tybaDB
      POSTGRES_PASSWORD: CHGjcu02*
      POSTGRES_DB: tybaDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
